#include "WeDoFramework_map.h"
#include "WeDoFramework_html_map.h"

int HTML_ID_Mapping(int id)
{
  switch(id)
  {
    case IDH___CLASSES                                         : return IDH_HTML___CLASSES;
    case IDH_TwclWeDoBatteryLevelService                       : return IDH_HTML_TwclWeDoBatteryLevelService;
    case IDH___MEMBEROVERVIEW_TwclWeDoBatteryLevelService      : return IDH_HTML___MEMBEROVERVIEW_TwclWeDoBatteryLevelService;
    case IDH_TwclWeDoBatteryLevelService_Create_TwclGattClient_TwclWeDoHub: return IDH_HTML_TwclWeDoBatteryLevelService_Create_TwclGattClient_TwclWeDoHub;
    case IDH___MEMBERTYPE_Methods_TwclWeDoBatteryLevelService  : return IDH_HTML___MEMBERTYPE_Methods_TwclWeDoBatteryLevelService;
    case IDH_TwclWeDoBatteryLevelService_DoBatteryLevelChanged_Byte: return IDH_HTML_TwclWeDoBatteryLevelService_DoBatteryLevelChanged_Byte;
    case IDH_TwclWeDoBatteryLevelService_Initialize            : return IDH_HTML_TwclWeDoBatteryLevelService_Initialize;
    case IDH_TwclWeDoBatteryLevelService_ReadBatteryLevel_Byte : return IDH_HTML_TwclWeDoBatteryLevelService_ReadBatteryLevel_Byte;
    case IDH_TwclWeDoBatteryLevelService_Uninitialize          : return IDH_HTML_TwclWeDoBatteryLevelService_Uninitialize;
    case IDH___MEMBERTYPE_Events_TwclWeDoBatteryLevelService   : return IDH_HTML___MEMBERTYPE_Events_TwclWeDoBatteryLevelService;
    case IDH_TwclWeDoBatteryLevelService_OnBatteryLevelChanged : return IDH_HTML_TwclWeDoBatteryLevelService_OnBatteryLevelChanged;
    case IDH_TwclWeDoCurrentSensor                             : return IDH_HTML_TwclWeDoCurrentSensor;
    case IDH___MEMBEROVERVIEW_TwclWeDoCurrentSensor            : return IDH_HTML___MEMBEROVERVIEW_TwclWeDoCurrentSensor;
    case IDH_TwclWeDoCurrentSensor_Create_TwclWeDoHub_Byte     : return IDH_HTML_TwclWeDoCurrentSensor_Create_TwclWeDoHub_Byte;
    case IDH___MEMBERTYPE_Methods_TwclWeDoCurrentSensor        : return IDH_HTML___MEMBERTYPE_Methods_TwclWeDoCurrentSensor;
    case IDH_TwclWeDoCurrentSensor_DoCurrentChanged            : return IDH_HTML_TwclWeDoCurrentSensor_DoCurrentChanged;
    case IDH_TwclWeDoCurrentSensor_ValueChanged                : return IDH_HTML_TwclWeDoCurrentSensor_ValueChanged;
    case IDH___MEMBERTYPE_Properties_TwclWeDoCurrentSensor     : return IDH_HTML___MEMBERTYPE_Properties_TwclWeDoCurrentSensor;
    case IDH_TwclWeDoCurrentSensor_Current                     : return IDH_HTML_TwclWeDoCurrentSensor_Current;
    case IDH_TwclWeDoCurrentSensor_OnCurrentChanged            : return IDH_HTML_TwclWeDoCurrentSensor_OnCurrentChanged;
    case IDH_TwclWeDoDataFormat                                : return IDH_HTML_TwclWeDoDataFormat;
    case IDH___MEMBEROVERVIEW_TwclWeDoDataFormat               : return IDH_HTML___MEMBEROVERVIEW_TwclWeDoDataFormat;
    case IDH_TwclWeDoDataFormat_Create_Byte_Byte_Byte_TwclWeDoSensorDataUnit: return IDH_HTML_TwclWeDoDataFormat_Create_Byte_Byte_Byte_TwclWeDoSensorDataUnit;
    case IDH___MEMBERTYPE_Properties_TwclWeDoDataFormat        : return IDH_HTML___MEMBERTYPE_Properties_TwclWeDoDataFormat;
    case IDH_TwclWeDoDataFormat_DataSetCount                   : return IDH_HTML_TwclWeDoDataFormat_DataSetCount;
    case IDH_TwclWeDoDataFormat_DataSetSize                    : return IDH_HTML_TwclWeDoDataFormat_DataSetSize;
    case IDH_TwclWeDoDataFormat_Mode                           : return IDH_HTML_TwclWeDoDataFormat_Mode;
    case IDH_TwclWeDoDataFormat_Unit_                          : return IDH_HTML_TwclWeDoDataFormat_Unit_;
    case IDH_TwclWeDoDeviceInformationService                  : return IDH_HTML_TwclWeDoDeviceInformationService;
    case IDH___MEMBEROVERVIEW_TwclWeDoDeviceInformationService : return IDH_HTML___MEMBEROVERVIEW_TwclWeDoDeviceInformationService;
    case IDH_TwclWeDoDeviceInformationService_Create_TwclGattClient_TwclWeDoHub: return IDH_HTML_TwclWeDoDeviceInformationService_Create_TwclGattClient_TwclWeDoHub;
    case IDH___MEMBERTYPE_Methods_TwclWeDoDeviceInformationService: return IDH_HTML___MEMBERTYPE_Methods_TwclWeDoDeviceInformationService;
    case IDH_TwclWeDoDeviceInformationService_Initialize       : return IDH_HTML_TwclWeDoDeviceInformationService_Initialize;
    case IDH_TwclWeDoDeviceInformationService_ReadFirmwareVersion_string: return IDH_HTML_TwclWeDoDeviceInformationService_ReadFirmwareVersion_string;
    case IDH_TwclWeDoDeviceInformationService_ReadHardwareVersion_string: return IDH_HTML_TwclWeDoDeviceInformationService_ReadHardwareVersion_string;
    case IDH_TwclWeDoDeviceInformationService_ReadManufacturerName_string: return IDH_HTML_TwclWeDoDeviceInformationService_ReadManufacturerName_string;
    case IDH_TwclWeDoDeviceInformationService_ReadSoftwareVersion_string: return IDH_HTML_TwclWeDoDeviceInformationService_ReadSoftwareVersion_string;
    case IDH_TwclWeDoDeviceInformationService_Uninitialize     : return IDH_HTML_TwclWeDoDeviceInformationService_Uninitialize;
    case IDH_TwclWeDoHub                                       : return IDH_HTML_TwclWeDoHub;
    case IDH___MEMBEROVERVIEW_TwclWeDoHub                      : return IDH_HTML___MEMBEROVERVIEW_TwclWeDoHub;
    case IDH_TwclWeDoHub_Create_TComponent                     : return IDH_HTML_TwclWeDoHub_Create_TComponent;
    case IDH_TwclWeDoHub_Destroy                               : return IDH_HTML_TwclWeDoHub_Destroy;
    case IDH___MEMBERTYPE_Methods_TwclWeDoHub                  : return IDH_HTML___MEMBERTYPE_Methods_TwclWeDoHub;
    case IDH_TwclWeDoHub_Connect_TwclBluetoothRadio_Int64      : return IDH_HTML_TwclWeDoHub_Connect_TwclBluetoothRadio_Int64;
    case IDH_TwclWeDoHub_Disconnect                            : return IDH_HTML_TwclWeDoHub_Disconnect;
    case IDH_TwclWeDoHub_DoButtonStateChanged_Boolean          : return IDH_HTML_TwclWeDoHub_DoButtonStateChanged_Boolean;
    case IDH_TwclWeDoHub_DoConnected_Integer                   : return IDH_HTML_TwclWeDoHub_DoConnected_Integer;
    case IDH_TwclWeDoHub_DoDeviceAttached_TwclWeDoIo           : return IDH_HTML_TwclWeDoHub_DoDeviceAttached_TwclWeDoIo;
    case IDH_TwclWeDoHub_DoDeviceDetached_TwclWeDoIo           : return IDH_HTML_TwclWeDoHub_DoDeviceDetached_TwclWeDoIo;
    case IDH_TwclWeDoHub_DoDisconnected_Integer                : return IDH_HTML_TwclWeDoHub_DoDisconnected_Integer;
    case IDH_TwclWeDoHub_DoHighCurrentAlert_Boolean            : return IDH_HTML_TwclWeDoHub_DoHighCurrentAlert_Boolean;
    case IDH_TwclWeDoHub_DoLowSignalAlert_Boolean              : return IDH_HTML_TwclWeDoHub_DoLowSignalAlert_Boolean;
    case IDH_TwclWeDoHub_DoLowVoltageAlert_Boolean             : return IDH_HTML_TwclWeDoHub_DoLowVoltageAlert_Boolean;
    case IDH_TwclWeDoHub_ReadDeviceName_string                 : return IDH_HTML_TwclWeDoHub_ReadDeviceName_string;
    case IDH_TwclWeDoHub_TurnOff                               : return IDH_HTML_TwclWeDoHub_TurnOff;
    case IDH_TwclWeDoHub_WriteDeviceName_string                : return IDH_HTML_TwclWeDoHub_WriteDeviceName_string;
    case IDH___MEMBERTYPE_Properties_TwclWeDoHub               : return IDH_HTML___MEMBERTYPE_Properties_TwclWeDoHub;
    case IDH_TwclWeDoHub_Address                               : return IDH_HTML_TwclWeDoHub_Address;
    case IDH_TwclWeDoHub_BatteryLevel                          : return IDH_HTML_TwclWeDoHub_BatteryLevel;
    case IDH_TwclWeDoHub_BatteryType                           : return IDH_HTML_TwclWeDoHub_BatteryType;
    case IDH_TwclWeDoHub_ClientState                           : return IDH_HTML_TwclWeDoHub_ClientState;
    case IDH_TwclWeDoHub_Connected                             : return IDH_HTML_TwclWeDoHub_Connected;
    case IDH_TwclWeDoHub_DeviceInformation                     : return IDH_HTML_TwclWeDoHub_DeviceInformation;
    case IDH_TwclWeDoHub_IoDevices                             : return IDH_HTML_TwclWeDoHub_IoDevices;
    case IDH___MEMBERTYPE_Events_TwclWeDoHub                   : return IDH_HTML___MEMBERTYPE_Events_TwclWeDoHub;
    case IDH_TwclWeDoHub_OnButtonStateChanged                  : return IDH_HTML_TwclWeDoHub_OnButtonStateChanged;
    case IDH_TwclWeDoHub_OnConnected                           : return IDH_HTML_TwclWeDoHub_OnConnected;
    case IDH_TwclWeDoHub_OnDeviceAttached                      : return IDH_HTML_TwclWeDoHub_OnDeviceAttached;
    case IDH_TwclWeDoHub_OnDeviceDetached                      : return IDH_HTML_TwclWeDoHub_OnDeviceDetached;
    case IDH_TwclWeDoHub_OnDisconnected                        : return IDH_HTML_TwclWeDoHub_OnDisconnected;
    case IDH_TwclWeDoHub_OnHighCurrentAlert                    : return IDH_HTML_TwclWeDoHub_OnHighCurrentAlert;
    case IDH_TwclWeDoHub_OnLowSignalAlert                      : return IDH_HTML_TwclWeDoHub_OnLowSignalAlert;
    case IDH_TwclWeDoHub_OnLowVoltageAlert                     : return IDH_HTML_TwclWeDoHub_OnLowVoltageAlert;
    case IDH_TwclWeDoHubService                                : return IDH_HTML_TwclWeDoHubService;
    case IDH___MEMBEROVERVIEW_TwclWeDoHubService               : return IDH_HTML___MEMBEROVERVIEW_TwclWeDoHubService;
    case IDH_TwclWeDoHubService_Create_TwclGattClient_TwclWeDoHub: return IDH_HTML_TwclWeDoHubService_Create_TwclGattClient_TwclWeDoHub;
    case IDH___MEMBERTYPE_Methods_TwclWeDoHubService           : return IDH_HTML___MEMBERTYPE_Methods_TwclWeDoHubService;
    case IDH_TwclWeDoHubService_DoButtonStateChanged_Boolean   : return IDH_HTML_TwclWeDoHubService_DoButtonStateChanged_Boolean;
    case IDH_TwclWeDoHubService_DoDeviceAttached_TwclWeDoIo    : return IDH_HTML_TwclWeDoHubService_DoDeviceAttached_TwclWeDoIo;
    case IDH_TwclWeDoHubService_DoDeviceDetached_Byte          : return IDH_HTML_TwclWeDoHubService_DoDeviceDetached_Byte;
    case IDH_TwclWeDoHubService_DoHightCurrentAlert_Boolean    : return IDH_HTML_TwclWeDoHubService_DoHightCurrentAlert_Boolean;
    case IDH_TwclWeDoHubService_DoLowSignalAlert_Boolean       : return IDH_HTML_TwclWeDoHubService_DoLowSignalAlert_Boolean;
    case IDH_TwclWeDoHubService_DoLowVoltageAlert_Boolean      : return IDH_HTML_TwclWeDoHubService_DoLowVoltageAlert_Boolean;
    case IDH_TwclWeDoHubService_Initialize                     : return IDH_HTML_TwclWeDoHubService_Initialize;
    case IDH_TwclWeDoHubService_Uninitialize                   : return IDH_HTML_TwclWeDoHubService_Uninitialize;
    case IDH_TwclWeDoInputFormat                               : return IDH_HTML_TwclWeDoInputFormat;
    case IDH___MEMBEROVERVIEW_TwclWeDoInputFormat              : return IDH_HTML___MEMBEROVERVIEW_TwclWeDoInputFormat;
    case IDH_TwclWeDoInputFormat_Create_Byte_TwclWeDoIoDeviceType_Byte_Cardinal_TwclWeDoSensorDataUnit: return IDH_HTML_TwclWeDoInputFormat_Create_Byte_TwclWeDoIoDeviceType_Byte_Cardinal_TwclWeDoSensorDataUnit;
    case IDH___MEMBERTYPE_Properties_TwclWeDoInputFormat       : return IDH_HTML___MEMBERTYPE_Properties_TwclWeDoInputFormat;
    case IDH_TwclWeDoInputFormat_ConnectionId                  : return IDH_HTML_TwclWeDoInputFormat_ConnectionId;
    case IDH_TwclWeDoInputFormat_DeviceType                    : return IDH_HTML_TwclWeDoInputFormat_DeviceType;
    case IDH_TwclWeDoInputFormat_Interval                      : return IDH_HTML_TwclWeDoInputFormat_Interval;
    case IDH_TwclWeDoInputFormat_Mode                          : return IDH_HTML_TwclWeDoInputFormat_Mode;
    case IDH_TwclWeDoInputFormat_NotificationsEnabled          : return IDH_HTML_TwclWeDoInputFormat_NotificationsEnabled;
    case IDH_TwclWeDoInputFormat_NumberOfBytes                 : return IDH_HTML_TwclWeDoInputFormat_NumberOfBytes;
    case IDH_TwclWeDoInputFormat_Revision                      : return IDH_HTML_TwclWeDoInputFormat_Revision;
    case IDH_TwclWeDoInputFormat_Unit_                         : return IDH_HTML_TwclWeDoInputFormat_Unit_;
    case IDH_TwclWeDoIo                                        : return IDH_HTML_TwclWeDoIo;
    case IDH___MEMBEROVERVIEW_TwclWeDoIo                       : return IDH_HTML___MEMBEROVERVIEW_TwclWeDoIo;
    case IDH_TwclWeDoIo_Create_TwclWeDoHub_Byte                : return IDH_HTML_TwclWeDoIo_Create_TwclWeDoHub_Byte;
    case IDH_TwclWeDoIo_Destroy                                : return IDH_HTML_TwclWeDoIo_Destroy;
    case IDH___MEMBERTYPE_Methods_TwclWeDoIo                   : return IDH_HTML___MEMBERTYPE_Methods_TwclWeDoIo;
    case IDH_TwclWeDoIo_AddValidDataFormat_IwclWeDoDataFormat  : return IDH_HTML_TwclWeDoIo_AddValidDataFormat_IwclWeDoDataFormat;
    case IDH_TwclWeDoIo_InputFormatChanged_IwclWeDoInputFormat : return IDH_HTML_TwclWeDoIo_InputFormatChanged_IwclWeDoInputFormat;
    case IDH_TwclWeDoIo_RemoveValidDataFormat_IwclWeDoDataFormat: return IDH_HTML_TwclWeDoIo_RemoveValidDataFormat_IwclWeDoDataFormat;
    case IDH_TwclWeDoIo_ResetSensor                            : return IDH_HTML_TwclWeDoIo_ResetSensor;
    case IDH_TwclWeDoIo_SendInputFormat_IwclWeDoInputFormat    : return IDH_HTML_TwclWeDoIo_SendInputFormat_IwclWeDoInputFormat;
    case IDH_TwclWeDoIo_SendReadValueRequest                   : return IDH_HTML_TwclWeDoIo_SendReadValueRequest;
    case IDH_TwclWeDoIo_SetInputFormatMode_Byte                : return IDH_HTML_TwclWeDoIo_SetInputFormatMode_Byte;
    case IDH_TwclWeDoIo_ValueChanged                           : return IDH_HTML_TwclWeDoIo_ValueChanged;
    case IDH_TwclWeDoIo_WriteData_TArray_Byte_                 : return IDH_HTML_TwclWeDoIo_WriteData_TArray_Byte_;
    case IDH___MEMBERTYPE_Properties_TwclWeDoIo                : return IDH_HTML___MEMBERTYPE_Properties_TwclWeDoIo;
    case IDH_TwclWeDoIo_AsFloat                                : return IDH_HTML_TwclWeDoIo_AsFloat;
    case IDH_TwclWeDoIo_AsInteger                              : return IDH_HTML_TwclWeDoIo_AsInteger;
    case IDH_TwclWeDoIo_Attached                               : return IDH_HTML_TwclWeDoIo_Attached;
    case IDH_TwclWeDoIo_ConnectionId                           : return IDH_HTML_TwclWeDoIo_ConnectionId;
    case IDH_TwclWeDoIo_DataFormats                            : return IDH_HTML_TwclWeDoIo_DataFormats;
    case IDH_TwclWeDoIo_DefaultInputFormat                     : return IDH_HTML_TwclWeDoIo_DefaultInputFormat;
    case IDH_TwclWeDoIo_DeviceType                             : return IDH_HTML_TwclWeDoIo_DeviceType;
    case IDH_TwclWeDoIo_FirmwareVersion                        : return IDH_HTML_TwclWeDoIo_FirmwareVersion;
    case IDH_TwclWeDoIo_HardwareVersion                        : return IDH_HTML_TwclWeDoIo_HardwareVersion;
    case IDH_TwclWeDoIo_Hub                                    : return IDH_HTML_TwclWeDoIo_Hub;
    case IDH_TwclWeDoIo_InputFormat                            : return IDH_HTML_TwclWeDoIo_InputFormat;
    case IDH_TwclWeDoIo_InputFormatMode                        : return IDH_HTML_TwclWeDoIo_InputFormatMode;
    case IDH_TwclWeDoIo_Internal                               : return IDH_HTML_TwclWeDoIo_Internal;
    case IDH_TwclWeDoIo_NumbersFromValueData                   : return IDH_HTML_TwclWeDoIo_NumbersFromValueData;
    case IDH_TwclWeDoIo_PortId                                 : return IDH_HTML_TwclWeDoIo_PortId;
    case IDH_TwclWeDoIo_Value                                  : return IDH_HTML_TwclWeDoIo_Value;
    case IDH_TwclWeDoIoService                                 : return IDH_HTML_TwclWeDoIoService;
    case IDH___MEMBEROVERVIEW_TwclWeDoIoService                : return IDH_HTML___MEMBEROVERVIEW_TwclWeDoIoService;
    case IDH_TwclWeDoIoService_Create_TwclGattClient_TwclWeDoHub: return IDH_HTML_TwclWeDoIoService_Create_TwclGattClient_TwclWeDoHub;
    case IDH_TwclWeDoIoService_Destroy                         : return IDH_HTML_TwclWeDoIoService_Destroy;
    case IDH___MEMBERTYPE_Methods_TwclWeDoIoService            : return IDH_HTML___MEMBERTYPE_Methods_TwclWeDoIoService;
    case IDH_TwclWeDoIoService_Initialize                      : return IDH_HTML_TwclWeDoIoService_Initialize;
    case IDH_TwclWeDoIoService_Uninitialize                    : return IDH_HTML_TwclWeDoIoService_Uninitialize;
    case IDH_TwclWeDoMotionSensor                              : return IDH_HTML_TwclWeDoMotionSensor;
    case IDH___MEMBEROVERVIEW_TwclWeDoMotionSensor             : return IDH_HTML___MEMBEROVERVIEW_TwclWeDoMotionSensor;
    case IDH_TwclWeDoMotionSensor_Create_TwclWeDoHub_Byte      : return IDH_HTML_TwclWeDoMotionSensor_Create_TwclWeDoHub_Byte;
    case IDH___MEMBERTYPE_Methods_TwclWeDoMotionSensor         : return IDH_HTML___MEMBERTYPE_Methods_TwclWeDoMotionSensor;
    case IDH_TwclWeDoMotionSensor_DoCountChanged               : return IDH_HTML_TwclWeDoMotionSensor_DoCountChanged;
    case IDH_TwclWeDoMotionSensor_DoDistanceChanged            : return IDH_HTML_TwclWeDoMotionSensor_DoDistanceChanged;
    case IDH_TwclWeDoMotionSensor_DoModeChanged                : return IDH_HTML_TwclWeDoMotionSensor_DoModeChanged;
    case IDH_TwclWeDoMotionSensor_InputFormatChanged_IwclWeDoInputFormat: return IDH_HTML_TwclWeDoMotionSensor_InputFormatChanged_IwclWeDoInputFormat;
    case IDH_TwclWeDoMotionSensor_SetMode_TwclWeDoMotionSensorMode: return IDH_HTML_TwclWeDoMotionSensor_SetMode_TwclWeDoMotionSensorMode;
    case IDH_TwclWeDoMotionSensor_ValueChanged                 : return IDH_HTML_TwclWeDoMotionSensor_ValueChanged;
    case IDH___MEMBERTYPE_Properties_TwclWeDoMotionSensor      : return IDH_HTML___MEMBERTYPE_Properties_TwclWeDoMotionSensor;
    case IDH_TwclWeDoMotionSensor_Count                        : return IDH_HTML_TwclWeDoMotionSensor_Count;
    case IDH_TwclWeDoMotionSensor_Distance                     : return IDH_HTML_TwclWeDoMotionSensor_Distance;
    case IDH_TwclWeDoMotionSensor_Mode                         : return IDH_HTML_TwclWeDoMotionSensor_Mode;
    case IDH_TwclWeDoMotionSensor_OnCountChanged               : return IDH_HTML_TwclWeDoMotionSensor_OnCountChanged;
    case IDH_TwclWeDoMotionSensor_OnDistanceChanged            : return IDH_HTML_TwclWeDoMotionSensor_OnDistanceChanged;
    case IDH_TwclWeDoMotionSensor_OnModeChanged                : return IDH_HTML_TwclWeDoMotionSensor_OnModeChanged;
    case IDH_TwclWeDoMotor                                     : return IDH_HTML_TwclWeDoMotor;
    case IDH___MEMBEROVERVIEW_TwclWeDoMotor                    : return IDH_HTML___MEMBEROVERVIEW_TwclWeDoMotor;
    case IDH_TwclWeDoMotor_Create_TwclWeDoHub_Byte             : return IDH_HTML_TwclWeDoMotor_Create_TwclWeDoHub_Byte;
    case IDH___MEMBERTYPE_Methods_TwclWeDoMotor                : return IDH_HTML___MEMBERTYPE_Methods_TwclWeDoMotor;
    case IDH_TwclWeDoMotor_Brake                               : return IDH_HTML_TwclWeDoMotor_Brake;
    case IDH_TwclWeDoMotor_Drift                               : return IDH_HTML_TwclWeDoMotor_Drift;
    case IDH_TwclWeDoMotor_Run_TwclWeDoMotorDirection_Byte     : return IDH_HTML_TwclWeDoMotor_Run_TwclWeDoMotorDirection_Byte;
    case IDH___MEMBERTYPE_Properties_TwclWeDoMotor             : return IDH_HTML___MEMBERTYPE_Properties_TwclWeDoMotor;
    case IDH_TwclWeDoMotor_Direction                           : return IDH_HTML_TwclWeDoMotor_Direction;
    case IDH_TwclWeDoMotor_IsBraking                           : return IDH_HTML_TwclWeDoMotor_IsBraking;
    case IDH_TwclWeDoMotor_IsDrifting                          : return IDH_HTML_TwclWeDoMotor_IsDrifting;
    case IDH_TwclWeDoMotor_Power                               : return IDH_HTML_TwclWeDoMotor_Power;
    case IDH_TwclWeDoPieazo                                    : return IDH_HTML_TwclWeDoPieazo;
    case IDH___MEMBEROVERVIEW_TwclWeDoPieazo                   : return IDH_HTML___MEMBEROVERVIEW_TwclWeDoPieazo;
    case IDH_TwclWeDoPieazo_Create_TwclWeDoHub_Byte            : return IDH_HTML_TwclWeDoPieazo_Create_TwclWeDoHub_Byte;
    case IDH___MEMBERTYPE_Methods_TwclWeDoPieazo               : return IDH_HTML___MEMBERTYPE_Methods_TwclWeDoPieazo;
    case IDH_TwclWeDoPieazo_PlayNote_TwclWeDoPiezoNote_Byte_Word: return IDH_HTML_TwclWeDoPieazo_PlayNote_TwclWeDoPiezoNote_Byte_Word;
    case IDH_TwclWeDoPieazo_PlayTone_Word_Word                 : return IDH_HTML_TwclWeDoPieazo_PlayTone_Word_Word;
    case IDH_TwclWeDoPieazo_StopPlaying                        : return IDH_HTML_TwclWeDoPieazo_StopPlaying;
    case IDH_TwclWeDoResetableSensor                           : return IDH_HTML_TwclWeDoResetableSensor;
    case IDH___MEMBEROVERVIEW_TwclWeDoResetableSensor          : return IDH_HTML___MEMBEROVERVIEW_TwclWeDoResetableSensor;
    case IDH_TwclWeDoResetableSensor_Create_TwclWeDoHub_Byte   : return IDH_HTML_TwclWeDoResetableSensor_Create_TwclWeDoHub_Byte;
    case IDH___MEMBERTYPE_Methods_TwclWeDoResetableSensor      : return IDH_HTML___MEMBERTYPE_Methods_TwclWeDoResetableSensor;
    case IDH_TwclWeDoResetableSensor_Reset                     : return IDH_HTML_TwclWeDoResetableSensor_Reset;
    case IDH_TwclWeDoRgbLight                                  : return IDH_HTML_TwclWeDoRgbLight;
    case IDH___MEMBEROVERVIEW_TwclWeDoRgbLight                 : return IDH_HTML___MEMBEROVERVIEW_TwclWeDoRgbLight;
    case IDH_TwclWeDoRgbLight_Create_TwclWeDoHub_Byte          : return IDH_HTML_TwclWeDoRgbLight_Create_TwclWeDoHub_Byte;
    case IDH___MEMBERTYPE_Methods_TwclWeDoRgbLight             : return IDH_HTML___MEMBERTYPE_Methods_TwclWeDoRgbLight;
    case IDH_TwclWeDoRgbLight_DoColorChanged                   : return IDH_HTML_TwclWeDoRgbLight_DoColorChanged;
    case IDH_TwclWeDoRgbLight_DoModeChanged                    : return IDH_HTML_TwclWeDoRgbLight_DoModeChanged;
    case IDH_TwclWeDoRgbLight_InputFormatChanged_IwclWeDoInputFormat: return IDH_HTML_TwclWeDoRgbLight_InputFormatChanged_IwclWeDoInputFormat;
    case IDH_TwclWeDoRgbLight_SetColor_TColor                  : return IDH_HTML_TwclWeDoRgbLight_SetColor_TColor;
    case IDH_TwclWeDoRgbLight_SetColorIndex_TwclWeDoColor      : return IDH_HTML_TwclWeDoRgbLight_SetColorIndex_TwclWeDoColor;
    case IDH_TwclWeDoRgbLight_SetMode_TwclWeDoRgbLightMode     : return IDH_HTML_TwclWeDoRgbLight_SetMode_TwclWeDoRgbLightMode;
    case IDH_TwclWeDoRgbLight_SwitchOff                        : return IDH_HTML_TwclWeDoRgbLight_SwitchOff;
    case IDH_TwclWeDoRgbLight_SwitchToDefaultColor             : return IDH_HTML_TwclWeDoRgbLight_SwitchToDefaultColor;
    case IDH_TwclWeDoRgbLight_ValueChanged                     : return IDH_HTML_TwclWeDoRgbLight_ValueChanged;
    case IDH___MEMBERTYPE_Properties_TwclWeDoRgbLight          : return IDH_HTML___MEMBERTYPE_Properties_TwclWeDoRgbLight;
    case IDH_TwclWeDoRgbLight_Color                            : return IDH_HTML_TwclWeDoRgbLight_Color;
    case IDH_TwclWeDoRgbLight_ColorIndex                       : return IDH_HTML_TwclWeDoRgbLight_ColorIndex;
    case IDH_TwclWeDoRgbLight_DefaultColor                     : return IDH_HTML_TwclWeDoRgbLight_DefaultColor;
    case IDH_TwclWeDoRgbLight_DefaultColorIndex                : return IDH_HTML_TwclWeDoRgbLight_DefaultColorIndex;
    case IDH_TwclWeDoRgbLight_Mode                             : return IDH_HTML_TwclWeDoRgbLight_Mode;
    case IDH_TwclWeDoRgbLight_OnColorChanged                   : return IDH_HTML_TwclWeDoRgbLight_OnColorChanged;
    case IDH_TwclWeDoRgbLight_OnModeChanged                    : return IDH_HTML_TwclWeDoRgbLight_OnModeChanged;
    case IDH_TwclWeDoService                                   : return IDH_HTML_TwclWeDoService;
    case IDH___MEMBEROVERVIEW_TwclWeDoService                  : return IDH_HTML___MEMBEROVERVIEW_TwclWeDoService;
    case IDH_TwclWeDoService_Create_TwclGattClient_TwclWeDoHub : return IDH_HTML_TwclWeDoService_Create_TwclGattClient_TwclWeDoHub;
    case IDH___MEMBERTYPE_Methods_TwclWeDoService              : return IDH_HTML___MEMBERTYPE_Methods_TwclWeDoService;
    case IDH_TwclWeDoService_CompareGuid_TwclGattUuid_TGUID    : return IDH_HTML_TwclWeDoService_CompareGuid_TwclGattUuid_TGUID;
    case IDH_TwclWeDoService_FindCharactersitc_TGUID_TwclGattService_TwclGattCharacteristic: return IDH_HTML_TwclWeDoService_FindCharactersitc_TGUID_TwclGattService_TwclGattCharacteristic;
    case IDH_TwclWeDoService_FindService_TGUID_TwclGattService : return IDH_HTML_TwclWeDoService_FindService_TGUID_TwclGattService;
    case IDH_TwclWeDoService_Initialize                        : return IDH_HTML_TwclWeDoService_Initialize;
    case IDH_TwclWeDoService_ReadByteValue_TwclGattCharacteristic_Byte: return IDH_HTML_TwclWeDoService_ReadByteValue_TwclGattCharacteristic_Byte;
    case IDH_TwclWeDoService_ReadStringValue_TwclGattCharacteristic_string: return IDH_HTML_TwclWeDoService_ReadStringValue_TwclGattCharacteristic_string;
    case IDH_TwclWeDoService_SubscribeForNotifications_TwclGattCharacteristic: return IDH_HTML_TwclWeDoService_SubscribeForNotifications_TwclGattCharacteristic;
    case IDH_TwclWeDoService_ToGuid_TwclGattUuid               : return IDH_HTML_TwclWeDoService_ToGuid_TwclGattUuid;
    case IDH_TwclWeDoService_Uninitialize                      : return IDH_HTML_TwclWeDoService_Uninitialize;
    case IDH_TwclWeDoService_UnsubscribeFromNotifications_TwclGattCharacteristic: return IDH_HTML_TwclWeDoService_UnsubscribeFromNotifications_TwclGattCharacteristic;
    case IDH___MEMBERTYPE_Properties_TwclWeDoService           : return IDH_HTML___MEMBERTYPE_Properties_TwclWeDoService;
    case IDH_TwclWeDoService_Client                            : return IDH_HTML_TwclWeDoService_Client;
    case IDH_TwclWeDoService_Hub                               : return IDH_HTML_TwclWeDoService_Hub;
    case IDH_TwclWeDoTiltSensor                                : return IDH_HTML_TwclWeDoTiltSensor;
    case IDH___MEMBEROVERVIEW_TwclWeDoTiltSensor               : return IDH_HTML___MEMBEROVERVIEW_TwclWeDoTiltSensor;
    case IDH_TwclWeDoTiltSensor_Create_TwclWeDoHub_Byte        : return IDH_HTML_TwclWeDoTiltSensor_Create_TwclWeDoHub_Byte;
    case IDH___MEMBERTYPE_Methods_TwclWeDoTiltSensor           : return IDH_HTML___MEMBERTYPE_Methods_TwclWeDoTiltSensor;
    case IDH_TwclWeDoTiltSensor_DoAngleChanged                 : return IDH_HTML_TwclWeDoTiltSensor_DoAngleChanged;
    case IDH_TwclWeDoTiltSensor_DoCrashChanged                 : return IDH_HTML_TwclWeDoTiltSensor_DoCrashChanged;
    case IDH_TwclWeDoTiltSensor_DoDirectionChanged             : return IDH_HTML_TwclWeDoTiltSensor_DoDirectionChanged;
    case IDH_TwclWeDoTiltSensor_DoModeChanged                  : return IDH_HTML_TwclWeDoTiltSensor_DoModeChanged;
    case IDH_TwclWeDoTiltSensor_InputFormatChanged_IwclWeDoInputFormat: return IDH_HTML_TwclWeDoTiltSensor_InputFormatChanged_IwclWeDoInputFormat;
    case IDH_TwclWeDoTiltSensor_SetMode_TwclWeDoTiltSensorMode : return IDH_HTML_TwclWeDoTiltSensor_SetMode_TwclWeDoTiltSensorMode;
    case IDH_TwclWeDoTiltSensor_ValueChanged                   : return IDH_HTML_TwclWeDoTiltSensor_ValueChanged;
    case IDH___MEMBERTYPE_Properties_TwclWeDoTiltSensor        : return IDH_HTML___MEMBERTYPE_Properties_TwclWeDoTiltSensor;
    case IDH_TwclWeDoTiltSensor_Angle                          : return IDH_HTML_TwclWeDoTiltSensor_Angle;
    case IDH_TwclWeDoTiltSensor_Crash                          : return IDH_HTML_TwclWeDoTiltSensor_Crash;
    case IDH_TwclWeDoTiltSensor_Direction                      : return IDH_HTML_TwclWeDoTiltSensor_Direction;
    case IDH_TwclWeDoTiltSensor_Mode                           : return IDH_HTML_TwclWeDoTiltSensor_Mode;
    case IDH_TwclWeDoTiltSensor_OnAngleChanged                 : return IDH_HTML_TwclWeDoTiltSensor_OnAngleChanged;
    case IDH_TwclWeDoTiltSensor_OnCrashChanged                 : return IDH_HTML_TwclWeDoTiltSensor_OnCrashChanged;
    case IDH_TwclWeDoTiltSensor_OnDirectionChanged             : return IDH_HTML_TwclWeDoTiltSensor_OnDirectionChanged;
    case IDH_TwclWeDoTiltSensor_OnModeChanged                  : return IDH_HTML_TwclWeDoTiltSensor_OnModeChanged;
    case IDH_TwclWeDoVersion                                   : return IDH_HTML_TwclWeDoVersion;
    case IDH___MEMBEROVERVIEW_TwclWeDoVersion                  : return IDH_HTML___MEMBEROVERVIEW_TwclWeDoVersion;
    case IDH___MEMBERTYPE_Fields_TwclWeDoVersion               : return IDH_HTML___MEMBERTYPE_Fields_TwclWeDoVersion;
    case IDH_TwclWeDoVersion_BugFixVersion                     : return IDH_HTML_TwclWeDoVersion_BugFixVersion;
    case IDH_TwclWeDoVersion_BuildNumber                       : return IDH_HTML_TwclWeDoVersion_BuildNumber;
    case IDH_TwclWeDoVersion_MajorVersion                      : return IDH_HTML_TwclWeDoVersion_MajorVersion;
    case IDH_TwclWeDoVersion_MinorVersion                      : return IDH_HTML_TwclWeDoVersion_MinorVersion;
    case IDH___MEMBERTYPE_Methods_TwclWeDoVersion              : return IDH_HTML___MEMBERTYPE_Methods_TwclWeDoVersion;
    case IDH_TwclWeDoVersion_ToString                          : return IDH_HTML_TwclWeDoVersion_ToString;
    case IDH_TwclWeDoVoltageSensor                             : return IDH_HTML_TwclWeDoVoltageSensor;
    case IDH___MEMBEROVERVIEW_TwclWeDoVoltageSensor            : return IDH_HTML___MEMBEROVERVIEW_TwclWeDoVoltageSensor;
    case IDH_TwclWeDoVoltageSensor_Create_TwclWeDoHub_Byte     : return IDH_HTML_TwclWeDoVoltageSensor_Create_TwclWeDoHub_Byte;
    case IDH___MEMBERTYPE_Methods_TwclWeDoVoltageSensor        : return IDH_HTML___MEMBERTYPE_Methods_TwclWeDoVoltageSensor;
    case IDH_TwclWeDoVoltageSensor_DoVoltageChanged            : return IDH_HTML_TwclWeDoVoltageSensor_DoVoltageChanged;
    case IDH_TwclWeDoVoltageSensor_ValueChanged                : return IDH_HTML_TwclWeDoVoltageSensor_ValueChanged;
    case IDH___MEMBERTYPE_Properties_TwclWeDoVoltageSensor     : return IDH_HTML___MEMBERTYPE_Properties_TwclWeDoVoltageSensor;
    case IDH_TwclWeDoVoltageSensor_OnVoltageChanged            : return IDH_HTML_TwclWeDoVoltageSensor_OnVoltageChanged;
    case IDH_TwclWeDoVoltageSensor_Voltage                     : return IDH_HTML_TwclWeDoVoltageSensor_Voltage;
    case IDH_TwclWeDoWatcher                                   : return IDH_HTML_TwclWeDoWatcher;
    case IDH___MEMBEROVERVIEW_TwclWeDoWatcher                  : return IDH_HTML___MEMBEROVERVIEW_TwclWeDoWatcher;
    case IDH_TwclWeDoWatcher_Create_TComponent                 : return IDH_HTML_TwclWeDoWatcher_Create_TComponent;
    case IDH___MEMBERTYPE_Methods_TwclWeDoWatcher              : return IDH_HTML___MEMBERTYPE_Methods_TwclWeDoWatcher;
    case IDH_TwclWeDoWatcher_DoHubFound_Int64_string           : return IDH_HTML_TwclWeDoWatcher_DoHubFound_Int64_string;
    case IDH_TwclWeDoWatcher_DoHubLost_Int64_string            : return IDH_HTML_TwclWeDoWatcher_DoHubLost_Int64_string;
    case IDH_TwclWeDoWatcher_DoHubNameChanged_Int64_string_string: return IDH_HTML_TwclWeDoWatcher_DoHubNameChanged_Int64_string_string;
    case IDH_TwclWeDoWatcher_DoStarted                         : return IDH_HTML_TwclWeDoWatcher_DoStarted;
    case IDH_TwclWeDoWatcher_DoStopped                         : return IDH_HTML_TwclWeDoWatcher_DoStopped;
    case IDH_TwclWeDoWatcher_Start_TwclBluetoothRadio          : return IDH_HTML_TwclWeDoWatcher_Start_TwclBluetoothRadio;
    case IDH_TwclWeDoWatcher_Stop                              : return IDH_HTML_TwclWeDoWatcher_Stop;
    case IDH___MEMBERTYPE_Properties_TwclWeDoWatcher           : return IDH_HTML___MEMBERTYPE_Properties_TwclWeDoWatcher;
    case IDH_TwclWeDoWatcher_Active                            : return IDH_HTML_TwclWeDoWatcher_Active;
    case IDH_TwclWeDoWatcher_OnStarted                         : return IDH_HTML_TwclWeDoWatcher_OnStarted;
    case IDH_TwclWeDoWatcher_OnStopped                         : return IDH_HTML_TwclWeDoWatcher_OnStopped;
    case IDH_TwclWeDoWatcher_Radio                             : return IDH_HTML_TwclWeDoWatcher_Radio;
    case IDH___MEMBERTYPE_Events_TwclWeDoWatcher               : return IDH_HTML___MEMBERTYPE_Events_TwclWeDoWatcher;
    case IDH_TwclWeDoWatcher_OnHubFound                        : return IDH_HTML_TwclWeDoWatcher_OnHubFound;
    case IDH_TwclWeDoWatcher_OnHubLost                         : return IDH_HTML_TwclWeDoWatcher_OnHubLost;
    case IDH_TwclWeDoWatcher_OnHubNameChanged                  : return IDH_HTML_TwclWeDoWatcher_OnHubNameChanged;
    case IDH___INTERFACES                                      : return IDH_HTML___INTERFACES;
    case IDH_IwclWeDoDataFormat                                : return IDH_HTML_IwclWeDoDataFormat;
    case IDH___MEMBEROVERVIEW_IwclWeDoDataFormat               : return IDH_HTML___MEMBEROVERVIEW_IwclWeDoDataFormat;
    case IDH___MEMBERTYPE_Methods_IwclWeDoDataFormat           : return IDH_HTML___MEMBERTYPE_Methods_IwclWeDoDataFormat;
    case IDH_IwclWeDoDataFormat_Obj                            : return IDH_HTML_IwclWeDoDataFormat_Obj;
    case IDH_IwclWeDoInputFormat                               : return IDH_HTML_IwclWeDoInputFormat;
    case IDH___MEMBEROVERVIEW_IwclWeDoInputFormat              : return IDH_HTML___MEMBEROVERVIEW_IwclWeDoInputFormat;
    case IDH___MEMBERTYPE_Methods_IwclWeDoInputFormat          : return IDH_HTML___MEMBERTYPE_Methods_IwclWeDoInputFormat;
    case IDH_IwclWeDoInputFormat_Equal_IwclWeDoInputFormat     : return IDH_HTML_IwclWeDoInputFormat_Equal_IwclWeDoInputFormat;
    case IDH_IwclWeDoInputFormat_Obj                           : return IDH_HTML_IwclWeDoInputFormat_Obj;
    case IDH___RECORDS                                         : return IDH_HTML___RECORDS;
    case IDH_TwclWeDoBatteryType                               : return IDH_HTML_TwclWeDoBatteryType;
    case IDH_TwclWeDoColor                                     : return IDH_HTML_TwclWeDoColor;
    case IDH_TwclWeDoIoDeviceType                              : return IDH_HTML_TwclWeDoIoDeviceType;
    case IDH_TwclWeDoMotionSensorMode                          : return IDH_HTML_TwclWeDoMotionSensorMode;
    case IDH_TwclWeDoMotorDirection                            : return IDH_HTML_TwclWeDoMotorDirection;
    case IDH_TwclWeDoPiezoNote                                 : return IDH_HTML_TwclWeDoPiezoNote;
    case IDH_TwclWeDoRgbLightMode                              : return IDH_HTML_TwclWeDoRgbLightMode;
    case IDH_TwclWeDoSensorDataUnit                            : return IDH_HTML_TwclWeDoSensorDataUnit;
    case IDH_TwclWeDoTiltSensorAngle                           : return IDH_HTML_TwclWeDoTiltSensorAngle;
    case IDH_TwclWeDoTiltSensorCrash                           : return IDH_HTML_TwclWeDoTiltSensorCrash;
    case IDH_TwclWeDoTiltSensorDirection                       : return IDH_HTML_TwclWeDoTiltSensorDirection;
    case IDH_TwclWeDoTiltSensorMode                            : return IDH_HTML_TwclWeDoTiltSensorMode;
    case IDH___TYPES                                           : return IDH_HTML___TYPES;
    case IDH_TwclBatteryLevelChangedEvent                      : return IDH_HTML_TwclBatteryLevelChangedEvent;
    case IDH_TwclWeDoDeviceStateChangedEvent                   : return IDH_HTML_TwclWeDoDeviceStateChangedEvent;
    case IDH_TwclWeDoHubAlertEvent                             : return IDH_HTML_TwclWeDoHubAlertEvent;
    case IDH_TwclWeDoHubAppearanceEvent                        : return IDH_HTML_TwclWeDoHubAppearanceEvent;
    case IDH_TwclWeDoHubButtonStateChangedEvent                : return IDH_HTML_TwclWeDoHubButtonStateChangedEvent;
    case IDH_TwclWeDoHubConnectEvent                           : return IDH_HTML_TwclWeDoHubConnectEvent;
    case IDH_TwclWeDoHubDisonnectEvent                         : return IDH_HTML_TwclWeDoHubDisonnectEvent;
    case IDH_TwclWeDoHubNameChangedEvent                       : return IDH_HTML_TwclWeDoHubNameChangedEvent;
    case IDH___CONSTANTS                                       : return IDH_HTML___CONSTANTS;
    case IDH_WCL_WEDO_GUID_NULL                                : return IDH_HTML_WCL_WEDO_GUID_NULL;
    case IDH___FILES                                           : return IDH_HTML___FILES;
    case IDH_wcl_inc                                           : return IDH_HTML_wcl_inc;
    case IDH_wclWeDoHub_pas                                    : return IDH_HTML_wclWeDoHub_pas;
    case IDH_wclWeDoWatcher_pas                                : return IDH_HTML_wclWeDoWatcher_pas;
    default: return -1;
  }
}
