#define IDH___CLASSES                                      0x00000000 // !!CLASSES
#define IDH_TwclWeDoBatteryLevelService                    0x00000001 // TwclWeDoBatteryLevelService
#define IDH___MEMBEROVERVIEW_TwclWeDoBatteryLevelService   0x00000002 // !!MEMBEROVERVIEW_TwclWeDoBatteryLevelService
#define IDH_TwclWeDoBatteryLevelService_Create_TwclGattClient_TwclWeDoHub 0x00000003 // TwclWeDoBatteryLevelService.Create@TwclGattClient@TwclWeDoHub
#define IDH___MEMBERTYPE_Methods_TwclWeDoBatteryLevelService 0x00000004 // !!MEMBERTYPE_Methods_TwclWeDoBatteryLevelService
#define IDH_TwclWeDoBatteryLevelService_DoBatteryLevelChanged_Byte 0x00000005 // TwclWeDoBatteryLevelService.DoBatteryLevelChanged@Byte
#define IDH_TwclWeDoBatteryLevelService_Initialize         0x00000006 // TwclWeDoBatteryLevelService.Initialize
#define IDH_TwclWeDoBatteryLevelService_ReadBatteryLevel_Byte 0x00000007 // TwclWeDoBatteryLevelService.ReadBatteryLevel@Byte
#define IDH_TwclWeDoBatteryLevelService_Uninitialize       0x00000008 // TwclWeDoBatteryLevelService.Uninitialize
#define IDH___MEMBERTYPE_Events_TwclWeDoBatteryLevelService 0x00000009 // !!MEMBERTYPE_Events_TwclWeDoBatteryLevelService
#define IDH_TwclWeDoBatteryLevelService_OnBatteryLevelChanged 0x0000000A // TwclWeDoBatteryLevelService.OnBatteryLevelChanged
#define IDH_TwclWeDoCurrentSensor                          0x0000000B // TwclWeDoCurrentSensor
#define IDH___MEMBEROVERVIEW_TwclWeDoCurrentSensor         0x0000000C // !!MEMBEROVERVIEW_TwclWeDoCurrentSensor
#define IDH_TwclWeDoCurrentSensor_Create_TwclWeDoHub_Byte  0x0000000D // TwclWeDoCurrentSensor.Create@TwclWeDoHub@Byte
#define IDH___MEMBERTYPE_Methods_TwclWeDoCurrentSensor     0x0000000E // !!MEMBERTYPE_Methods_TwclWeDoCurrentSensor
#define IDH_TwclWeDoCurrentSensor_DoCurrentChanged         0x0000000F // TwclWeDoCurrentSensor.DoCurrentChanged
#define IDH_TwclWeDoCurrentSensor_ValueChanged             0x00000010 // TwclWeDoCurrentSensor.ValueChanged
#define IDH___MEMBERTYPE_Properties_TwclWeDoCurrentSensor  0x00000011 // !!MEMBERTYPE_Properties_TwclWeDoCurrentSensor
#define IDH_TwclWeDoCurrentSensor_Current                  0x00000012 // TwclWeDoCurrentSensor.Current
#define IDH_TwclWeDoCurrentSensor_OnCurrentChanged         0x00000013 // TwclWeDoCurrentSensor.OnCurrentChanged
#define IDH_TwclWeDoDataFormat                             0x00000014 // TwclWeDoDataFormat
#define IDH___MEMBEROVERVIEW_TwclWeDoDataFormat            0x00000015 // !!MEMBEROVERVIEW_TwclWeDoDataFormat
#define IDH_TwclWeDoDataFormat_Create_Byte_Byte_Byte_TwclWeDoSensorDataUnit 0x00000016 // TwclWeDoDataFormat.Create@Byte@Byte@Byte@TwclWeDoSensorDataUnit
#define IDH___MEMBERTYPE_Properties_TwclWeDoDataFormat     0x00000017 // !!MEMBERTYPE_Properties_TwclWeDoDataFormat
#define IDH_TwclWeDoDataFormat_DataSetCount                0x00000018 // TwclWeDoDataFormat.DataSetCount
#define IDH_TwclWeDoDataFormat_DataSetSize                 0x00000019 // TwclWeDoDataFormat.DataSetSize
#define IDH_TwclWeDoDataFormat_Mode                        0x0000001A // TwclWeDoDataFormat.Mode
#define IDH_TwclWeDoDataFormat_Unit_                       0x0000001B // TwclWeDoDataFormat.Unit_
#define IDH_TwclWeDoDeviceInformationService               0x0000001C // TwclWeDoDeviceInformationService
#define IDH___MEMBEROVERVIEW_TwclWeDoDeviceInformationService 0x0000001D // !!MEMBEROVERVIEW_TwclWeDoDeviceInformationService
#define IDH_TwclWeDoDeviceInformationService_Create_TwclGattClient_TwclWeDoHub 0x0000001E // TwclWeDoDeviceInformationService.Create@TwclGattClient@TwclWeDoHub
#define IDH___MEMBERTYPE_Methods_TwclWeDoDeviceInformationService 0x0000001F // !!MEMBERTYPE_Methods_TwclWeDoDeviceInformationService
#define IDH_TwclWeDoDeviceInformationService_Initialize    0x00000020 // TwclWeDoDeviceInformationService.Initialize
#define IDH_TwclWeDoDeviceInformationService_ReadFirmwareVersion_string 0x00000021 // TwclWeDoDeviceInformationService.ReadFirmwareVersion@string
#define IDH_TwclWeDoDeviceInformationService_ReadHardwareVersion_string 0x00000022 // TwclWeDoDeviceInformationService.ReadHardwareVersion@string
#define IDH_TwclWeDoDeviceInformationService_ReadManufacturerName_string 0x00000023 // TwclWeDoDeviceInformationService.ReadManufacturerName@string
#define IDH_TwclWeDoDeviceInformationService_ReadSoftwareVersion_string 0x00000024 // TwclWeDoDeviceInformationService.ReadSoftwareVersion@string
#define IDH_TwclWeDoDeviceInformationService_Uninitialize  0x00000025 // TwclWeDoDeviceInformationService.Uninitialize
#define IDH_TwclWeDoHub                                    0x00000026 // TwclWeDoHub
#define IDH___MEMBEROVERVIEW_TwclWeDoHub                   0x00000027 // !!MEMBEROVERVIEW_TwclWeDoHub
#define IDH_TwclWeDoHub_Create_TComponent                  0x00000028 // TwclWeDoHub.Create@TComponent
#define IDH_TwclWeDoHub_Destroy                            0x00000029 // TwclWeDoHub.Destroy
#define IDH___MEMBERTYPE_Methods_TwclWeDoHub               0x0000002A // !!MEMBERTYPE_Methods_TwclWeDoHub
#define IDH_TwclWeDoHub_Connect_TwclBluetoothRadio_Int64   0x0000002B // TwclWeDoHub.Connect@TwclBluetoothRadio@Int64
#define IDH_TwclWeDoHub_Disconnect                         0x0000002C // TwclWeDoHub.Disconnect
#define IDH_TwclWeDoHub_DoButtonStateChanged_Boolean       0x0000002D // TwclWeDoHub.DoButtonStateChanged@Boolean
#define IDH_TwclWeDoHub_DoConnected_Integer                0x0000002E // TwclWeDoHub.DoConnected@Integer
#define IDH_TwclWeDoHub_DoDeviceAttached_TwclWeDoIo        0x0000002F // TwclWeDoHub.DoDeviceAttached@TwclWeDoIo
#define IDH_TwclWeDoHub_DoDeviceDetached_TwclWeDoIo        0x00000030 // TwclWeDoHub.DoDeviceDetached@TwclWeDoIo
#define IDH_TwclWeDoHub_DoDisconnected_Integer             0x00000031 // TwclWeDoHub.DoDisconnected@Integer
#define IDH_TwclWeDoHub_DoHighCurrentAlert_Boolean         0x00000032 // TwclWeDoHub.DoHighCurrentAlert@Boolean
#define IDH_TwclWeDoHub_DoLowSignalAlert_Boolean           0x00000033 // TwclWeDoHub.DoLowSignalAlert@Boolean
#define IDH_TwclWeDoHub_DoLowVoltageAlert_Boolean          0x00000034 // TwclWeDoHub.DoLowVoltageAlert@Boolean
#define IDH_TwclWeDoHub_ReadDeviceName_string              0x00000035 // TwclWeDoHub.ReadDeviceName@string
#define IDH_TwclWeDoHub_TurnOff                            0x00000036 // TwclWeDoHub.TurnOff
#define IDH_TwclWeDoHub_WriteDeviceName_string             0x00000037 // TwclWeDoHub.WriteDeviceName@string
#define IDH___MEMBERTYPE_Properties_TwclWeDoHub            0x00000038 // !!MEMBERTYPE_Properties_TwclWeDoHub
#define IDH_TwclWeDoHub_Address                            0x00000039 // TwclWeDoHub.Address
#define IDH_TwclWeDoHub_BatteryLevel                       0x0000003A // TwclWeDoHub.BatteryLevel
#define IDH_TwclWeDoHub_BatteryType                        0x0000003B // TwclWeDoHub.BatteryType
#define IDH_TwclWeDoHub_ClientState                        0x0000003C // TwclWeDoHub.ClientState
#define IDH_TwclWeDoHub_Connected                          0x0000003D // TwclWeDoHub.Connected
#define IDH_TwclWeDoHub_DeviceInformation                  0x0000003E // TwclWeDoHub.DeviceInformation
#define IDH_TwclWeDoHub_IoDevices                          0x0000003F // TwclWeDoHub.IoDevices
#define IDH___MEMBERTYPE_Events_TwclWeDoHub                0x00000040 // !!MEMBERTYPE_Events_TwclWeDoHub
#define IDH_TwclWeDoHub_OnButtonStateChanged               0x00000041 // TwclWeDoHub.OnButtonStateChanged
#define IDH_TwclWeDoHub_OnConnected                        0x00000042 // TwclWeDoHub.OnConnected
#define IDH_TwclWeDoHub_OnDeviceAttached                   0x00000043 // TwclWeDoHub.OnDeviceAttached
#define IDH_TwclWeDoHub_OnDeviceDetached                   0x00000044 // TwclWeDoHub.OnDeviceDetached
#define IDH_TwclWeDoHub_OnDisconnected                     0x00000045 // TwclWeDoHub.OnDisconnected
#define IDH_TwclWeDoHub_OnHighCurrentAlert                 0x00000046 // TwclWeDoHub.OnHighCurrentAlert
#define IDH_TwclWeDoHub_OnLowSignalAlert                   0x00000047 // TwclWeDoHub.OnLowSignalAlert
#define IDH_TwclWeDoHub_OnLowVoltageAlert                  0x00000048 // TwclWeDoHub.OnLowVoltageAlert
#define IDH_TwclWeDoHubService                             0x00000049 // TwclWeDoHubService
#define IDH___MEMBEROVERVIEW_TwclWeDoHubService            0x0000004A // !!MEMBEROVERVIEW_TwclWeDoHubService
#define IDH_TwclWeDoHubService_Create_TwclGattClient_TwclWeDoHub 0x0000004B // TwclWeDoHubService.Create@TwclGattClient@TwclWeDoHub
#define IDH___MEMBERTYPE_Methods_TwclWeDoHubService        0x0000004C // !!MEMBERTYPE_Methods_TwclWeDoHubService
#define IDH_TwclWeDoHubService_DoButtonStateChanged_Boolean 0x0000004D // TwclWeDoHubService.DoButtonStateChanged@Boolean
#define IDH_TwclWeDoHubService_DoDeviceAttached_TwclWeDoIo 0x0000004E // TwclWeDoHubService.DoDeviceAttached@TwclWeDoIo
#define IDH_TwclWeDoHubService_DoDeviceDetached_Byte       0x0000004F // TwclWeDoHubService.DoDeviceDetached@Byte
#define IDH_TwclWeDoHubService_DoHightCurrentAlert_Boolean 0x00000050 // TwclWeDoHubService.DoHightCurrentAlert@Boolean
#define IDH_TwclWeDoHubService_DoLowSignalAlert_Boolean    0x00000051 // TwclWeDoHubService.DoLowSignalAlert@Boolean
#define IDH_TwclWeDoHubService_DoLowVoltageAlert_Boolean   0x00000052 // TwclWeDoHubService.DoLowVoltageAlert@Boolean
#define IDH_TwclWeDoHubService_Initialize                  0x00000053 // TwclWeDoHubService.Initialize
#define IDH_TwclWeDoHubService_Uninitialize                0x00000054 // TwclWeDoHubService.Uninitialize
#define IDH_TwclWeDoInputFormat                            0x00000055 // TwclWeDoInputFormat
#define IDH___MEMBEROVERVIEW_TwclWeDoInputFormat           0x00000056 // !!MEMBEROVERVIEW_TwclWeDoInputFormat
#define IDH_TwclWeDoInputFormat_Create_Byte_TwclWeDoIoDeviceType_Byte_Cardinal_TwclWeDoSensorDataUnit 0x00000057 // TwclWeDoInputFormat.Create@Byte@TwclWeDoIoDeviceType@Byte@Cardinal@TwclWeDoSensorDataUnit@Boolean@Byte@Byte
#define IDH___MEMBERTYPE_Properties_TwclWeDoInputFormat    0x00000058 // !!MEMBERTYPE_Properties_TwclWeDoInputFormat
#define IDH_TwclWeDoInputFormat_ConnectionId               0x00000059 // TwclWeDoInputFormat.ConnectionId
#define IDH_TwclWeDoInputFormat_DeviceType                 0x0000005A // TwclWeDoInputFormat.DeviceType
#define IDH_TwclWeDoInputFormat_Interval                   0x0000005B // TwclWeDoInputFormat.Interval
#define IDH_TwclWeDoInputFormat_Mode                       0x0000005C // TwclWeDoInputFormat.Mode
#define IDH_TwclWeDoInputFormat_NotificationsEnabled       0x0000005D // TwclWeDoInputFormat.NotificationsEnabled
#define IDH_TwclWeDoInputFormat_NumberOfBytes              0x0000005E // TwclWeDoInputFormat.NumberOfBytes
#define IDH_TwclWeDoInputFormat_Revision                   0x0000005F // TwclWeDoInputFormat.Revision
#define IDH_TwclWeDoInputFormat_Unit_                      0x00000060 // TwclWeDoInputFormat.Unit_
#define IDH_TwclWeDoIo                                     0x00000061 // TwclWeDoIo
#define IDH___MEMBEROVERVIEW_TwclWeDoIo                    0x00000062 // !!MEMBEROVERVIEW_TwclWeDoIo
#define IDH_TwclWeDoIo_Create_TwclWeDoHub_Byte             0x00000063 // TwclWeDoIo.Create@TwclWeDoHub@Byte
#define IDH_TwclWeDoIo_Destroy                             0x00000064 // TwclWeDoIo.Destroy
#define IDH___MEMBERTYPE_Methods_TwclWeDoIo                0x00000065 // !!MEMBERTYPE_Methods_TwclWeDoIo
#define IDH_TwclWeDoIo_AddValidDataFormat_IwclWeDoDataFormat 0x00000066 // TwclWeDoIo.AddValidDataFormat@IwclWeDoDataFormat
#define IDH_TwclWeDoIo_InputFormatChanged_IwclWeDoInputFormat 0x00000067 // TwclWeDoIo.InputFormatChanged@IwclWeDoInputFormat
#define IDH_TwclWeDoIo_RemoveValidDataFormat_IwclWeDoDataFormat 0x00000068 // TwclWeDoIo.RemoveValidDataFormat@IwclWeDoDataFormat
#define IDH_TwclWeDoIo_ResetSensor                         0x00000069 // TwclWeDoIo.ResetSensor
#define IDH_TwclWeDoIo_SendInputFormat_IwclWeDoInputFormat 0x0000006A // TwclWeDoIo.SendInputFormat@IwclWeDoInputFormat
#define IDH_TwclWeDoIo_SendReadValueRequest                0x0000006B // TwclWeDoIo.SendReadValueRequest
#define IDH_TwclWeDoIo_SetInputFormatMode_Byte             0x0000006C // TwclWeDoIo.SetInputFormatMode@Byte
#define IDH_TwclWeDoIo_ValueChanged                        0x0000006D // TwclWeDoIo.ValueChanged
#define IDH_TwclWeDoIo_WriteData_TArray_Byte_              0x0000006E // TwclWeDoIo.WriteData@TArray<Byte>
#define IDH___MEMBERTYPE_Properties_TwclWeDoIo             0x0000006F // !!MEMBERTYPE_Properties_TwclWeDoIo
#define IDH_TwclWeDoIo_AsFloat                             0x00000070 // TwclWeDoIo.AsFloat
#define IDH_TwclWeDoIo_AsInteger                           0x00000071 // TwclWeDoIo.AsInteger
#define IDH_TwclWeDoIo_Attached                            0x00000072 // TwclWeDoIo.Attached
#define IDH_TwclWeDoIo_ConnectionId                        0x00000073 // TwclWeDoIo.ConnectionId
#define IDH_TwclWeDoIo_DataFormats                         0x00000074 // TwclWeDoIo.DataFormats
#define IDH_TwclWeDoIo_DefaultInputFormat                  0x00000075 // TwclWeDoIo.DefaultInputFormat
#define IDH_TwclWeDoIo_DeviceType                          0x00000076 // TwclWeDoIo.DeviceType
#define IDH_TwclWeDoIo_FirmwareVersion                     0x00000077 // TwclWeDoIo.FirmwareVersion
#define IDH_TwclWeDoIo_HardwareVersion                     0x00000078 // TwclWeDoIo.HardwareVersion
#define IDH_TwclWeDoIo_Hub                                 0x00000079 // TwclWeDoIo.Hub
#define IDH_TwclWeDoIo_InputFormat                         0x0000007A // TwclWeDoIo.InputFormat
#define IDH_TwclWeDoIo_InputFormatMode                     0x0000007B // TwclWeDoIo.InputFormatMode
#define IDH_TwclWeDoIo_Internal                            0x0000007C // TwclWeDoIo.Internal
#define IDH_TwclWeDoIo_NumbersFromValueData                0x0000007D // TwclWeDoIo.NumbersFromValueData
#define IDH_TwclWeDoIo_PortId                              0x0000007E // TwclWeDoIo.PortId
#define IDH_TwclWeDoIo_Value                               0x0000007F // TwclWeDoIo.Value
#define IDH_TwclWeDoIoService                              0x00000080 // TwclWeDoIoService
#define IDH___MEMBEROVERVIEW_TwclWeDoIoService             0x00000081 // !!MEMBEROVERVIEW_TwclWeDoIoService
#define IDH_TwclWeDoIoService_Create_TwclGattClient_TwclWeDoHub 0x00000082 // TwclWeDoIoService.Create@TwclGattClient@TwclWeDoHub
#define IDH_TwclWeDoIoService_Destroy                      0x00000083 // TwclWeDoIoService.Destroy
#define IDH___MEMBERTYPE_Methods_TwclWeDoIoService         0x00000084 // !!MEMBERTYPE_Methods_TwclWeDoIoService
#define IDH_TwclWeDoIoService_Initialize                   0x00000085 // TwclWeDoIoService.Initialize
#define IDH_TwclWeDoIoService_Uninitialize                 0x00000086 // TwclWeDoIoService.Uninitialize
#define IDH_TwclWeDoMotionSensor                           0x00000087 // TwclWeDoMotionSensor
#define IDH___MEMBEROVERVIEW_TwclWeDoMotionSensor          0x00000088 // !!MEMBEROVERVIEW_TwclWeDoMotionSensor
#define IDH_TwclWeDoMotionSensor_Create_TwclWeDoHub_Byte   0x00000089 // TwclWeDoMotionSensor.Create@TwclWeDoHub@Byte
#define IDH___MEMBERTYPE_Methods_TwclWeDoMotionSensor      0x0000008A // !!MEMBERTYPE_Methods_TwclWeDoMotionSensor
#define IDH_TwclWeDoMotionSensor_DoCountChanged            0x0000008B // TwclWeDoMotionSensor.DoCountChanged
#define IDH_TwclWeDoMotionSensor_DoDistanceChanged         0x0000008C // TwclWeDoMotionSensor.DoDistanceChanged
#define IDH_TwclWeDoMotionSensor_DoModeChanged             0x0000008D // TwclWeDoMotionSensor.DoModeChanged
#define IDH_TwclWeDoMotionSensor_InputFormatChanged_IwclWeDoInputFormat 0x0000008E // TwclWeDoMotionSensor.InputFormatChanged@IwclWeDoInputFormat
#define IDH_TwclWeDoMotionSensor_SetMode_TwclWeDoMotionSensorMode 0x0000008F // TwclWeDoMotionSensor.SetMode@TwclWeDoMotionSensorMode
#define IDH_TwclWeDoMotionSensor_ValueChanged              0x00000090 // TwclWeDoMotionSensor.ValueChanged
#define IDH___MEMBERTYPE_Properties_TwclWeDoMotionSensor   0x00000091 // !!MEMBERTYPE_Properties_TwclWeDoMotionSensor
#define IDH_TwclWeDoMotionSensor_Count                     0x00000092 // TwclWeDoMotionSensor.Count
#define IDH_TwclWeDoMotionSensor_Distance                  0x00000093 // TwclWeDoMotionSensor.Distance
#define IDH_TwclWeDoMotionSensor_Mode                      0x00000094 // TwclWeDoMotionSensor.Mode
#define IDH_TwclWeDoMotionSensor_OnCountChanged            0x00000095 // TwclWeDoMotionSensor.OnCountChanged
#define IDH_TwclWeDoMotionSensor_OnDistanceChanged         0x00000096 // TwclWeDoMotionSensor.OnDistanceChanged
#define IDH_TwclWeDoMotionSensor_OnModeChanged             0x00000097 // TwclWeDoMotionSensor.OnModeChanged
#define IDH_TwclWeDoMotor                                  0x00000098 // TwclWeDoMotor
#define IDH___MEMBEROVERVIEW_TwclWeDoMotor                 0x00000099 // !!MEMBEROVERVIEW_TwclWeDoMotor
#define IDH_TwclWeDoMotor_Create_TwclWeDoHub_Byte          0x0000009A // TwclWeDoMotor.Create@TwclWeDoHub@Byte
#define IDH___MEMBERTYPE_Methods_TwclWeDoMotor             0x0000009B // !!MEMBERTYPE_Methods_TwclWeDoMotor
#define IDH_TwclWeDoMotor_Brake                            0x0000009C // TwclWeDoMotor.Brake
#define IDH_TwclWeDoMotor_Drift                            0x0000009D // TwclWeDoMotor.Drift
#define IDH_TwclWeDoMotor_Run_TwclWeDoMotorDirection_Byte  0x0000009E // TwclWeDoMotor.Run@TwclWeDoMotorDirection@Byte
#define IDH___MEMBERTYPE_Properties_TwclWeDoMotor          0x0000009F // !!MEMBERTYPE_Properties_TwclWeDoMotor
#define IDH_TwclWeDoMotor_Direction                        0x000000A0 // TwclWeDoMotor.Direction
#define IDH_TwclWeDoMotor_IsBraking                        0x000000A1 // TwclWeDoMotor.IsBraking
#define IDH_TwclWeDoMotor_IsDrifting                       0x000000A2 // TwclWeDoMotor.IsDrifting
#define IDH_TwclWeDoMotor_Power                            0x000000A3 // TwclWeDoMotor.Power
#define IDH_TwclWeDoPieazo                                 0x000000A4 // TwclWeDoPieazo
#define IDH___MEMBEROVERVIEW_TwclWeDoPieazo                0x000000A5 // !!MEMBEROVERVIEW_TwclWeDoPieazo
#define IDH_TwclWeDoPieazo_Create_TwclWeDoHub_Byte         0x000000A6 // TwclWeDoPieazo.Create@TwclWeDoHub@Byte
#define IDH___MEMBERTYPE_Methods_TwclWeDoPieazo            0x000000A7 // !!MEMBERTYPE_Methods_TwclWeDoPieazo
#define IDH_TwclWeDoPieazo_PlayNote_TwclWeDoPiezoNote_Byte_Word 0x000000A8 // TwclWeDoPieazo.PlayNote@TwclWeDoPiezoNote@Byte@Word
#define IDH_TwclWeDoPieazo_PlayTone_Word_Word              0x000000A9 // TwclWeDoPieazo.PlayTone@Word@Word
#define IDH_TwclWeDoPieazo_StopPlaying                     0x000000AA // TwclWeDoPieazo.StopPlaying
#define IDH_TwclWeDoResetableSensor                        0x000000AB // TwclWeDoResetableSensor
#define IDH___MEMBEROVERVIEW_TwclWeDoResetableSensor       0x000000AC // !!MEMBEROVERVIEW_TwclWeDoResetableSensor
#define IDH_TwclWeDoResetableSensor_Create_TwclWeDoHub_Byte 0x000000AD // TwclWeDoResetableSensor.Create@TwclWeDoHub@Byte
#define IDH___MEMBERTYPE_Methods_TwclWeDoResetableSensor   0x000000AE // !!MEMBERTYPE_Methods_TwclWeDoResetableSensor
#define IDH_TwclWeDoResetableSensor_Reset                  0x000000AF // TwclWeDoResetableSensor.Reset
#define IDH_TwclWeDoRgbLight                               0x000000B0 // TwclWeDoRgbLight
#define IDH___MEMBEROVERVIEW_TwclWeDoRgbLight              0x000000B1 // !!MEMBEROVERVIEW_TwclWeDoRgbLight
#define IDH_TwclWeDoRgbLight_Create_TwclWeDoHub_Byte       0x000000B2 // TwclWeDoRgbLight.Create@TwclWeDoHub@Byte
#define IDH___MEMBERTYPE_Methods_TwclWeDoRgbLight          0x000000B3 // !!MEMBERTYPE_Methods_TwclWeDoRgbLight
#define IDH_TwclWeDoRgbLight_DoColorChanged                0x000000B4 // TwclWeDoRgbLight.DoColorChanged
#define IDH_TwclWeDoRgbLight_DoModeChanged                 0x000000B5 // TwclWeDoRgbLight.DoModeChanged
#define IDH_TwclWeDoRgbLight_InputFormatChanged_IwclWeDoInputFormat 0x000000B6 // TwclWeDoRgbLight.InputFormatChanged@IwclWeDoInputFormat
#define IDH_TwclWeDoRgbLight_SetColor_TColor               0x000000B7 // TwclWeDoRgbLight.SetColor@TColor
#define IDH_TwclWeDoRgbLight_SetColorIndex_TwclWeDoColor   0x000000B8 // TwclWeDoRgbLight.SetColorIndex@TwclWeDoColor
#define IDH_TwclWeDoRgbLight_SetMode_TwclWeDoRgbLightMode  0x000000B9 // TwclWeDoRgbLight.SetMode@TwclWeDoRgbLightMode
#define IDH_TwclWeDoRgbLight_SwitchOff                     0x000000BA // TwclWeDoRgbLight.SwitchOff
#define IDH_TwclWeDoRgbLight_SwitchToDefaultColor          0x000000BB // TwclWeDoRgbLight.SwitchToDefaultColor
#define IDH_TwclWeDoRgbLight_ValueChanged                  0x000000BC // TwclWeDoRgbLight.ValueChanged
#define IDH___MEMBERTYPE_Properties_TwclWeDoRgbLight       0x000000BD // !!MEMBERTYPE_Properties_TwclWeDoRgbLight
#define IDH_TwclWeDoRgbLight_Color                         0x000000BE // TwclWeDoRgbLight.Color
#define IDH_TwclWeDoRgbLight_ColorIndex                    0x000000BF // TwclWeDoRgbLight.ColorIndex
#define IDH_TwclWeDoRgbLight_DefaultColor                  0x000000C0 // TwclWeDoRgbLight.DefaultColor
#define IDH_TwclWeDoRgbLight_DefaultColorIndex             0x000000C1 // TwclWeDoRgbLight.DefaultColorIndex
#define IDH_TwclWeDoRgbLight_Mode                          0x000000C2 // TwclWeDoRgbLight.Mode
#define IDH_TwclWeDoRgbLight_OnColorChanged                0x000000C3 // TwclWeDoRgbLight.OnColorChanged
#define IDH_TwclWeDoRgbLight_OnModeChanged                 0x000000C4 // TwclWeDoRgbLight.OnModeChanged
#define IDH_TwclWeDoService                                0x000000C5 // TwclWeDoService
#define IDH___MEMBEROVERVIEW_TwclWeDoService               0x000000C6 // !!MEMBEROVERVIEW_TwclWeDoService
#define IDH_TwclWeDoService_Create_TwclGattClient_TwclWeDoHub 0x000000C7 // TwclWeDoService.Create@TwclGattClient@TwclWeDoHub
#define IDH___MEMBERTYPE_Methods_TwclWeDoService           0x000000C8 // !!MEMBERTYPE_Methods_TwclWeDoService
#define IDH_TwclWeDoService_CompareGuid_TwclGattUuid_TGUID 0x000000C9 // TwclWeDoService.CompareGuid@TwclGattUuid@TGUID
#define IDH_TwclWeDoService_FindCharactersitc_TGUID_TwclGattService_TwclGattCharacteristic 0x000000CA // TwclWeDoService.FindCharactersitc@TGUID@TwclGattService@TwclGattCharacteristic
#define IDH_TwclWeDoService_FindService_TGUID_TwclGattService 0x000000CB // TwclWeDoService.FindService@TGUID@TwclGattService
#define IDH_TwclWeDoService_Initialize                     0x000000CC // TwclWeDoService.Initialize
#define IDH_TwclWeDoService_ReadByteValue_TwclGattCharacteristic_Byte 0x000000CD // TwclWeDoService.ReadByteValue@TwclGattCharacteristic@Byte
#define IDH_TwclWeDoService_ReadStringValue_TwclGattCharacteristic_string 0x000000CE // TwclWeDoService.ReadStringValue@TwclGattCharacteristic@string
#define IDH_TwclWeDoService_SubscribeForNotifications_TwclGattCharacteristic 0x000000CF // TwclWeDoService.SubscribeForNotifications@TwclGattCharacteristic
#define IDH_TwclWeDoService_ToGuid_TwclGattUuid            0x000000D0 // TwclWeDoService.ToGuid@TwclGattUuid
#define IDH_TwclWeDoService_Uninitialize                   0x000000D1 // TwclWeDoService.Uninitialize
#define IDH_TwclWeDoService_UnsubscribeFromNotifications_TwclGattCharacteristic 0x000000D2 // TwclWeDoService.UnsubscribeFromNotifications@TwclGattCharacteristic
#define IDH___MEMBERTYPE_Properties_TwclWeDoService        0x000000D3 // !!MEMBERTYPE_Properties_TwclWeDoService
#define IDH_TwclWeDoService_Client                         0x000000D4 // TwclWeDoService.Client
#define IDH_TwclWeDoService_Hub                            0x000000D5 // TwclWeDoService.Hub
#define IDH_TwclWeDoTiltSensor                             0x000000D6 // TwclWeDoTiltSensor
#define IDH___MEMBEROVERVIEW_TwclWeDoTiltSensor            0x000000D7 // !!MEMBEROVERVIEW_TwclWeDoTiltSensor
#define IDH_TwclWeDoTiltSensor_Create_TwclWeDoHub_Byte     0x000000D8 // TwclWeDoTiltSensor.Create@TwclWeDoHub@Byte
#define IDH___MEMBERTYPE_Methods_TwclWeDoTiltSensor        0x000000D9 // !!MEMBERTYPE_Methods_TwclWeDoTiltSensor
#define IDH_TwclWeDoTiltSensor_DoAngleChanged              0x000000DA // TwclWeDoTiltSensor.DoAngleChanged
#define IDH_TwclWeDoTiltSensor_DoCrashChanged              0x000000DB // TwclWeDoTiltSensor.DoCrashChanged
#define IDH_TwclWeDoTiltSensor_DoDirectionChanged          0x000000DC // TwclWeDoTiltSensor.DoDirectionChanged
#define IDH_TwclWeDoTiltSensor_DoModeChanged               0x000000DD // TwclWeDoTiltSensor.DoModeChanged
#define IDH_TwclWeDoTiltSensor_InputFormatChanged_IwclWeDoInputFormat 0x000000DE // TwclWeDoTiltSensor.InputFormatChanged@IwclWeDoInputFormat
#define IDH_TwclWeDoTiltSensor_SetMode_TwclWeDoTiltSensorMode 0x000000DF // TwclWeDoTiltSensor.SetMode@TwclWeDoTiltSensorMode
#define IDH_TwclWeDoTiltSensor_ValueChanged                0x000000E0 // TwclWeDoTiltSensor.ValueChanged
#define IDH___MEMBERTYPE_Properties_TwclWeDoTiltSensor     0x000000E1 // !!MEMBERTYPE_Properties_TwclWeDoTiltSensor
#define IDH_TwclWeDoTiltSensor_Angle                       0x000000E2 // TwclWeDoTiltSensor.Angle
#define IDH_TwclWeDoTiltSensor_Crash                       0x000000E3 // TwclWeDoTiltSensor.Crash
#define IDH_TwclWeDoTiltSensor_Direction                   0x000000E4 // TwclWeDoTiltSensor.Direction
#define IDH_TwclWeDoTiltSensor_Mode                        0x000000E5 // TwclWeDoTiltSensor.Mode
#define IDH_TwclWeDoTiltSensor_OnAngleChanged              0x000000E6 // TwclWeDoTiltSensor.OnAngleChanged
#define IDH_TwclWeDoTiltSensor_OnCrashChanged              0x000000E7 // TwclWeDoTiltSensor.OnCrashChanged
#define IDH_TwclWeDoTiltSensor_OnDirectionChanged          0x000000E8 // TwclWeDoTiltSensor.OnDirectionChanged
#define IDH_TwclWeDoTiltSensor_OnModeChanged               0x000000E9 // TwclWeDoTiltSensor.OnModeChanged
#define IDH_TwclWeDoVersion                                0x000000EA // TwclWeDoVersion
#define IDH___MEMBEROVERVIEW_TwclWeDoVersion               0x000000EB // !!MEMBEROVERVIEW_TwclWeDoVersion
#define IDH___MEMBERTYPE_Fields_TwclWeDoVersion            0x000000EC // !!MEMBERTYPE_Fields_TwclWeDoVersion
#define IDH_TwclWeDoVersion_BugFixVersion                  0x000000ED // TwclWeDoVersion.BugFixVersion
#define IDH_TwclWeDoVersion_BuildNumber                    0x000000EE // TwclWeDoVersion.BuildNumber
#define IDH_TwclWeDoVersion_MajorVersion                   0x000000EF // TwclWeDoVersion.MajorVersion
#define IDH_TwclWeDoVersion_MinorVersion                   0x000000F0 // TwclWeDoVersion.MinorVersion
#define IDH___MEMBERTYPE_Methods_TwclWeDoVersion           0x000000F1 // !!MEMBERTYPE_Methods_TwclWeDoVersion
#define IDH_TwclWeDoVersion_ToString                       0x000000F2 // TwclWeDoVersion.ToString
#define IDH_TwclWeDoVoltageSensor                          0x000000F3 // TwclWeDoVoltageSensor
#define IDH___MEMBEROVERVIEW_TwclWeDoVoltageSensor         0x000000F4 // !!MEMBEROVERVIEW_TwclWeDoVoltageSensor
#define IDH_TwclWeDoVoltageSensor_Create_TwclWeDoHub_Byte  0x000000F5 // TwclWeDoVoltageSensor.Create@TwclWeDoHub@Byte
#define IDH___MEMBERTYPE_Methods_TwclWeDoVoltageSensor     0x000000F6 // !!MEMBERTYPE_Methods_TwclWeDoVoltageSensor
#define IDH_TwclWeDoVoltageSensor_DoVoltageChanged         0x000000F7 // TwclWeDoVoltageSensor.DoVoltageChanged
#define IDH_TwclWeDoVoltageSensor_ValueChanged             0x000000F8 // TwclWeDoVoltageSensor.ValueChanged
#define IDH___MEMBERTYPE_Properties_TwclWeDoVoltageSensor  0x000000F9 // !!MEMBERTYPE_Properties_TwclWeDoVoltageSensor
#define IDH_TwclWeDoVoltageSensor_OnVoltageChanged         0x000000FA // TwclWeDoVoltageSensor.OnVoltageChanged
#define IDH_TwclWeDoVoltageSensor_Voltage                  0x000000FB // TwclWeDoVoltageSensor.Voltage
#define IDH_TwclWeDoWatcher                                0x000000FC // TwclWeDoWatcher
#define IDH___MEMBEROVERVIEW_TwclWeDoWatcher               0x000000FD // !!MEMBEROVERVIEW_TwclWeDoWatcher
#define IDH_TwclWeDoWatcher_Create_TComponent              0x000000FE // TwclWeDoWatcher.Create@TComponent
#define IDH___MEMBERTYPE_Methods_TwclWeDoWatcher           0x000000FF // !!MEMBERTYPE_Methods_TwclWeDoWatcher
#define IDH_TwclWeDoWatcher_DoHubFound_Int64_string        0x00000100 // TwclWeDoWatcher.DoHubFound@Int64@string
#define IDH_TwclWeDoWatcher_DoHubLost_Int64_string         0x00000101 // TwclWeDoWatcher.DoHubLost@Int64@string
#define IDH_TwclWeDoWatcher_DoHubNameChanged_Int64_string_string 0x00000102 // TwclWeDoWatcher.DoHubNameChanged@Int64@string@string
#define IDH_TwclWeDoWatcher_DoStarted                      0x00000103 // TwclWeDoWatcher.DoStarted
#define IDH_TwclWeDoWatcher_DoStopped                      0x00000104 // TwclWeDoWatcher.DoStopped
#define IDH_TwclWeDoWatcher_Start_TwclBluetoothRadio       0x00000105 // TwclWeDoWatcher.Start@TwclBluetoothRadio
#define IDH_TwclWeDoWatcher_Stop                           0x00000106 // TwclWeDoWatcher.Stop
#define IDH___MEMBERTYPE_Properties_TwclWeDoWatcher        0x00000107 // !!MEMBERTYPE_Properties_TwclWeDoWatcher
#define IDH_TwclWeDoWatcher_Active                         0x00000108 // TwclWeDoWatcher.Active
#define IDH_TwclWeDoWatcher_OnStarted                      0x00000109 // TwclWeDoWatcher.OnStarted
#define IDH_TwclWeDoWatcher_OnStopped                      0x0000010A // TwclWeDoWatcher.OnStopped
#define IDH_TwclWeDoWatcher_Radio                          0x0000010B // TwclWeDoWatcher.Radio
#define IDH___MEMBERTYPE_Events_TwclWeDoWatcher            0x0000010C // !!MEMBERTYPE_Events_TwclWeDoWatcher
#define IDH_TwclWeDoWatcher_OnHubFound                     0x0000010D // TwclWeDoWatcher.OnHubFound
#define IDH_TwclWeDoWatcher_OnHubLost                      0x0000010E // TwclWeDoWatcher.OnHubLost
#define IDH_TwclWeDoWatcher_OnHubNameChanged               0x0000010F // TwclWeDoWatcher.OnHubNameChanged
#define IDH___INTERFACES                                   0x00000110 // !!INTERFACES
#define IDH_IwclWeDoDataFormat                             0x00000111 // IwclWeDoDataFormat
#define IDH___MEMBEROVERVIEW_IwclWeDoDataFormat            0x00000112 // !!MEMBEROVERVIEW_IwclWeDoDataFormat
#define IDH___MEMBERTYPE_Methods_IwclWeDoDataFormat        0x00000113 // !!MEMBERTYPE_Methods_IwclWeDoDataFormat
#define IDH_IwclWeDoDataFormat_Obj                         0x00000114 // IwclWeDoDataFormat.Obj
#define IDH_IwclWeDoInputFormat                            0x00000115 // IwclWeDoInputFormat
#define IDH___MEMBEROVERVIEW_IwclWeDoInputFormat           0x00000116 // !!MEMBEROVERVIEW_IwclWeDoInputFormat
#define IDH___MEMBERTYPE_Methods_IwclWeDoInputFormat       0x00000117 // !!MEMBERTYPE_Methods_IwclWeDoInputFormat
#define IDH_IwclWeDoInputFormat_Equal_IwclWeDoInputFormat  0x00000118 // IwclWeDoInputFormat.Equal@IwclWeDoInputFormat
#define IDH_IwclWeDoInputFormat_Obj                        0x00000119 // IwclWeDoInputFormat.Obj
#define IDH___RECORDS                                      0x0000011A // !!RECORDS
#define IDH_TwclWeDoBatteryType                            0x0000011B // TwclWeDoBatteryType
#define IDH_TwclWeDoColor                                  0x0000011C // TwclWeDoColor
#define IDH_TwclWeDoIoDeviceType                           0x0000011D // TwclWeDoIoDeviceType
#define IDH_TwclWeDoMotionSensorMode                       0x0000011E // TwclWeDoMotionSensorMode
#define IDH_TwclWeDoMotorDirection                         0x0000011F // TwclWeDoMotorDirection
#define IDH_TwclWeDoPiezoNote                              0x00000120 // TwclWeDoPiezoNote
#define IDH_TwclWeDoRgbLightMode                           0x00000121 // TwclWeDoRgbLightMode
#define IDH_TwclWeDoSensorDataUnit                         0x00000122 // TwclWeDoSensorDataUnit
#define IDH_TwclWeDoTiltSensorAngle                        0x00000123 // TwclWeDoTiltSensorAngle
#define IDH_TwclWeDoTiltSensorCrash                        0x00000124 // TwclWeDoTiltSensorCrash
#define IDH_TwclWeDoTiltSensorDirection                    0x00000125 // TwclWeDoTiltSensorDirection
#define IDH_TwclWeDoTiltSensorMode                         0x00000126 // TwclWeDoTiltSensorMode
#define IDH___TYPES                                        0x00000127 // !!TYPES
#define IDH_TwclBatteryLevelChangedEvent                   0x00000128 // TwclBatteryLevelChangedEvent
#define IDH_TwclWeDoDeviceStateChangedEvent                0x00000129 // TwclWeDoDeviceStateChangedEvent
#define IDH_TwclWeDoHubAlertEvent                          0x0000012A // TwclWeDoHubAlertEvent
#define IDH_TwclWeDoHubAppearanceEvent                     0x0000012B // TwclWeDoHubAppearanceEvent
#define IDH_TwclWeDoHubButtonStateChangedEvent             0x0000012C // TwclWeDoHubButtonStateChangedEvent
#define IDH_TwclWeDoHubConnectEvent                        0x0000012D // TwclWeDoHubConnectEvent
#define IDH_TwclWeDoHubDisonnectEvent                      0x0000012E // TwclWeDoHubDisonnectEvent
#define IDH_TwclWeDoHubNameChangedEvent                    0x0000012F // TwclWeDoHubNameChangedEvent
#define IDH___CONSTANTS                                    0x00000130 // !!CONSTANTS
#define IDH_WCL_WEDO_GUID_NULL                             0x00000131 // WCL_WEDO_GUID_NULL
#define IDH___FILES                                        0x00000132 // !!FILES
#define IDH_wcl_inc                                        0x00000133 // wcl.inc
#define IDH_wclWeDoHub_pas                                 0x00000134 // wclWeDoHub.pas
#define IDH_wclWeDoWatcher_pas                             0x00000135 // wclWeDoWatcher.pas
